sudo: required
services:
  - docker

before_install:
  - docker build -t federicofernanus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true federicofernanus/docker-react npm run test -- --coverage